version: '3.6'

services:
  node:
    container_name: file_experience_node_1
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: ${STAGE}
    ports:
      - "8089:8089"
      - "9229:9229"
    labels:
      - traefik.http.routers.api.rule=Host(`api.domain.com`)
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=lets-encrypt
      - traefik.port=80
    volumes:
      - ./dist:/home/node/app/dist
      - ./src:/home/node/app/src
      - ./config:/home/node/app/config:cached
      - ./.env:/home/node/app/.env
    networks:
     - file_service_net

  db:
    container_name: file_experience_db_1
    restart: always
    build:
      context: docker/mongo/
      dockerfile: Dockerfile
    ports:
      - "27018:27017"
    networks:
     - file_service_net
    environment:
      MONGODB_ROOT_PASSWORD: 123456
      MONGODB_USERNAME: file_experience
      MONGODB_PASSWORD: file_experience
      MONGODB_DATABASE: file_experience
    volumes:
      - data:/bitnami/mongodb

  minio:
    container_name: file_experience_minio_1
    restart: always
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    labels:
      - traefik.http.routers.api.rule=Host(`minio.domain.com`)
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
     - file_service_net
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: 12345678
      MINIO_DOMAIN: localhost
    volumes:
      - minio:/data
    command: server --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 /data

  redis:
    image: bitnami/redis:latest
    restart: always
    container_name: file_experience_redis_1
    environment:
      - REDIS_PASSWORD=ewsua132435 # Security reasons
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG # Security reasons
    ports:
      - "6379:6379"
    networks:
     - file_service_net
    volumes:
      - redis:/bitnami/redis/data

networks:
  file_service_net:
    driver: "bridge"

volumes:
  data:
    driver: "local"
  minio:
    driver: "local"
  redis:
    driver: "local"
