version: 2.1
jobs:
  test:
    working_directory: ~/circleci
    docker:
      - image: cimg/node:18.14
    steps:
      - checkout
      - run: echo "Running tests"
      - run: npm install --force
      - run: npm run ci
      - run: npm run build-tsc
      - run: npm run test-ci
      - store_artifacts:
          path: ~/circleci/coverage
          destination: reports/

workflows:
  version: 2
  test_build:
    jobs:
      - test
    filters:
      branches:
        only: master
      tags:
        only: /^\d+\.\d+\.\d+$/
